### ISSUE TITLE
[Bug] Incompatible with future versions of Paper

### ISSUE THREAD

**Issue by untuned** [frafol/CleanPing#5]
This is a heads-up since this will only be an issue in the future, but due to parsing the CB relocation version directly, CleanPing will break on Paper in the future.
Here is more info on the topic/how to resolve it: https://forums.papermc.io/threads/paper-velocity-1-20-4.998/#post-2955
Use this server jar for testing: https://github.com/PaperMC/testing/releases/tag/no-relocation

Stacktrace:
```
[20:18:06 ERROR]: Error occurred while enabling CleanPing v1.5.1 (Is it up to date?)
java.lang.ArrayIndexOutOfBoundsException: Index 3 out of bounds for length 3
        at it.frafol.cleanping.bukkit.CleanPing.onEnable(CleanPing.java:85) ~[CleanPing.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:287) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:188) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.CraftServer.enablePlugin(CraftServer.java:639) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at org.bukkit.craftbukkit.CraftServer.enablePlugins(CraftServer.java:550) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:671) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:431) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:309) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1133) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:319) ~[paper-1.20.4.jar:git-Paper-"84a586f"]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
```

**Comment by frafol** [comment]
> [10:36:37 INFO]: Time elapsed: 200 ms
> [10:36:37 INFO]: [CleanPing] Server version: 1.20.4-R0.1-SNAPSHOT
> [10:36:37 INFO]: [CleanPing] Loading configuration...
> [10:36:37 INFO]: [CleanPing] Loading commands...
> [10:36:37 INFO]: [CleanPing] Metrics loaded successfully!
> [10:36:37 INFO]: [CleanPing] Plugin successfully loaded!

Now it works correctly.
